# Generated by Django 5.1.5 on 2025-02-05 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employerprofile',
            name='company_description',
        ),
    ]
