# Generated by Django 5.1.5 on 2025-02-05 11:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_employerprofile_company_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='employerprofile',
            name='cuurent_position',
            field=models.CharField(default=datetime.time(0, 0), max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employerprofile',
            name='qualification_certificate',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
