# Generated by Django 5.1.5 on 2025-02-05 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_employerprofile_cuurent_position_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employerprofile',
            name='qualification_certificate',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
    ]
